---
title: "playground"
output: html_document
---

### Reading in data

```{r}
library(shiny)
library(tidyverse)
library(lubridate)
library(dplyr)
library(scales) 
library(RColorBrewer)
library(plotly)
library(ggplot2)
#library(kableExtra)

# Read in the data
print( "Loading data ..." )
fda_approvals <- read.csv('FDA_Drug_Trials_Snapshots_2015-20.csv')
disease_burden <- read.csv('Disease_burden.csv')
print( "Data loaded!" )

# Change class type of select variables to aid in data processing and visualization
fda_approvals$Enrollment <- as.numeric(as.character(fda_approvals$Enrollment))
fda_approvals$Therapeutic_Area <- as.character(fda_approvals$Therapeutic_Area)
fda_approvals$Brand_Name <- as.character(fda_approvals$Brand_Name)
fda_approvals$United_States <- as.numeric(as.character(fda_approvals$United_States))

# Add columns for non-hispanic, Men, Age under 65 
fda_approvals <- fda_approvals %>% mutate(Non_Hispanic = 100 - Hispanic, .after = Hispanic)
fda_approvals <- fda_approvals %>% mutate(Male = 100 - Female, .after = Female)
fda_approvals <- fda_approvals %>% mutate(Age_under_65 = 100 - Age_65_or_older, .after = Age_65_or_older)

# Create longer version, for plotting
fda_approvals_long <- pivot_longer(fda_approvals, cols = Female:Age_80_or_older, names_to = "Demographic", values_to = "Percentage")

# Change class type of variable in long
fda_approvals_long$Percentage <- as.numeric(as.character(fda_approvals_long$Percentage))

# Make 15-19 dataset
approvals_15_19 <- fda_approvals %>% filter(Approval_Year != 2020)

```


### Page 9 recreation

```{r}
## To account for missing data, we capture % representation of each demographic only in trials where that demographic is captured

# Race

global_black_participation <- approvals_15_19 %>% 
    select(Brand_Name, Enrollment, Black) %>% 
    filter(Black != "NA") %>% 
    mutate(Black_participants = (Black/100) * Enrollment)

global_white_participation <- approvals_15_19 %>% 
    select(Brand_Name, Enrollment, White) %>% 
    filter(White != "NA") %>% 
    mutate(White_participants = (White/100) * Enrollment)

global_asian_participation <- approvals_15_19 %>% 
    select(Brand_Name, Enrollment, Asian) %>% 
    filter(Asian != "NA") %>% 
    mutate(Asian_participants = (Asian/100) * Enrollment)

race_participation <- c(round(sum(100 * global_asian_participation$Asian_participants) /
                                         sum(global_asian_participation$Enrollment), 0), 
                               round(sum(100 * global_black_participation$Black_participants) / 
                                         sum(global_black_participation$Enrollment), 0),
                               round(sum(100 * global_white_participation$White_participants) / 
                                         sum(global_white_participation$Enrollment), 0))

races <- c("Asian", "Black", "White")
race_participation <- data.frame("Race", races, race_participation)
names(ace_participation) <- c("Demographic", "Category", "Value")

# Sex

global_female_participation <- approvals_15_19 %>% 
    select(Brand_Name, Enrollment, Female) %>% 
    filter(Female != "NA") %>% 
    mutate(Female_participants = (Female/100) * Enrollment)

global_male_participation <- approvals_15_19 %>%
    select(Brand_Name, Enrollment, Male) %>% 
    filter(Male != "NA") %>% 
    mutate(Male_participants = (Male/100) * Enrollment)

sex_participation <- c(round(sum(100 * global_female_participation$Female_participants) /
                                         sum(global_female_participation$Enrollment), 0), 
                               round(sum(100 * global_male_participation$Male_participants) / 
                                         sum(global_male_participation$Enrollment), 0))

sexes <- c("Female", "Male")
sex_participation <- data.frame("Sex", sexes, sex_participation)
names(sex_participation) <- c("Demographic", "Category", "Value")

# Age

global_Age_under_65_participation <- approvals_15_19 %>% 
    select(Brand_Name, Enrollment, Age_under_65) %>% 
    filter(Age_under_65 != "NA") %>% 
    mutate(Age_under_65_participants = (Age_under_65/100) * Enrollment)

global_Age_65_or_older_participation <- approvals_15_19 %>%
    select(Brand_Name, Enrollment, Age_65_or_older) %>% 
    filter(Age_65_or_older != "NA") %>% 
    mutate(Age_65_or_older_participants = (Age_65_or_older/100) * Enrollment)

age_participation <- c(round(sum(100 * global_Age_under_65_participation$Age_under_65_participants) /
                                         sum(global_Age_under_65_participation$Enrollment), 0), 
                               round(sum(100 * global_Age_65_or_older_participation$Age_65_or_older_participants) / 
                                         sum(global_Age_65_or_older_participation$Enrollment), 0))

ages <- c("Age_under_65", "Age_65_or_older")
age_participation <- data.frame("Age", ages, age_participation)
names(age_participation) <- c("Demographic", "Category", "Value")

# Combine the tables
demographic_participation <- rbind(age_participation, sex_participation, race_participation)

```


```{r}

demographic_participation_graph <- demographic_participation %>% 
  ggplot(aes(x = Category, y = Value)) +
  geom_col(width = 0.5) + 
  geom_text(aes(label = Value), position = position_dodge(0.9), vjust=-0.4, size=4) +
  expand_limits(y=c(0, 100)) +
  facet_wrap(~Demographic, scales = "free")

demographic_participation_graph
  
```



```{r}

demographic_participation_graph <- demographic_participation %>% 
    pivot_longer(cols = Value, names_to = "Database", values_to = "Participation") %>% 
    ggplot(aes(Race, Participation, width = 0.5)) + #, fill = Database)) +
    geom_bar(stat = "identity", position = 'dodge') +
    geom_text(aes(label=Participation), position = position_dodge(0.9), vjust=-0.3, size=6) +
    ylim(0,100) +
    xlab("Race") +
    ylab("Participation") + 
    #theme(text = element_text(size=15), axis.text.x = element_text(size=15)) +
    theme(axis.title.x=element_text(size=12, face="bold"), axis.title.y=element_text(size=12, face="bold")) +
    ggtitle("Race distribution of trial participants")

demographic_participation_graph

```

### Explore averages

```{r}

trash <- fda_approvals %>% 
  filter(Approval_Year == 2019) %>% 
  filter(Hispanic != "NA") %>% 
  select(Brand_Name, Approval_Year, Enrollment, Hispanic)

mean(trash$Hispanic)
trash <- trash %>% 
  mutate(SumProd = Enrollment * Hispanic / 100)
sum(trash$SumProd) / sum(trash$Enrollment)


```


```{r}


# Calculate mean representation treating weighting each trial by enrollment size
averages <- fda_approvals_long %>% filter(Percentage != "NA") # create new df with non NA participation

averages <- averages %>% # Calculate number of people (% representation * Trial Enrollment)
  mutate(Population = round((Percentage / 100) * Enrollment))

averages_all_years <- averages %>% # Calculate weighted average (Demographic groups' enrollment / Total Enrollment) - all years
  group_by(Demographic) %>% 
  summarize(Demographic_enrollment = sum(Population), Total_enrollment = sum(Enrollment)) %>% 
  mutate(Weighted_average = 100* Demographic_enrollment / Total_enrollment)

averages <- averages %>% # Same as above but by year
  group_by(Approval_Year, Demographic) %>% 
  summarize(Demographic_enrollment = sum(Population), Total_enrollment = sum(Enrollment)) %>% 
  mutate(Weighted_average = 100* Demographic_enrollment / Total_enrollment)

# Calculate median representation
approval_median <- fda_approvals_long %>% filter(Percentage != "NA") # create new df with non NA participation

approval_median_all_years <- approval_median %>% # Calculate median enrollment percentage across all trials
  group_by(Demographic) %>% 
  summarize(Median = median(Percentage))

approval_median <- approval_median %>% # Same as above but by year
  group_by(Approval_Year, Demographic) %>% 
  summarize(Median = median(Percentage))

# Calculate mean representation treating each trial equally
approval_mean <- fda_approvals_long %>% filter(Percentage != "NA") # create new df with non NA participation

approval_mean_all_years <- approval_mean %>% # Calculate mean enrollment percentage across all trials (non weighted by enrollment)
  group_by(Demographic) %>% 
  summarize(Average = mean(Percentage))

approval_mean <- approval_mean %>% # Same as above but by year
  group_by(Approval_Year, Demographic) %>% 
  summarize(Average = mean(Percentage))

# Create combined dataset by Demographic
summary_statistics_all_years <- data.frame(averages_all_years$Demographic, approval_median_all_years$Median, approval_mean_all_years$Average, averages_all_years$Weighted_average)
names(summary_statistics_all_years) <- c("Demographic", "Median", "Average", "Weighted_average")

# Create combined dataset by Year and Demographic
summary_statistics <- data.frame(averages$Approval_Year, averages$Demographic, approval_median$Median, approval_mean$Average, averages$Weighted_average)
names(summary_statistics) <- c("Approval_Year", "Demographic", "Median", "Average", "Weighted_average")

summary_statistics
summary_statistics_all_years

```


```{r}
trashy <- fda_approvals_long %>% filter(Demographic != "Asian")
demographics_selected <- trashy %>% select(Demographic) %>% unique()
                
summary_statistics_all_years %>% filter(Demographic %in% demographics_selected$Demographic)


```


```{r}

dems <- c("White", "Black", "Asian")

#changes <-  %>% filter(Demographic %in% dems)

fda_approvals_long %>% 
  filter(Demographic %in% dems) %>% 
  filter(Percentage != "NA") %>% 
  ggplot(aes(x = Demographic, y = Percentage, fill = factor(Approval_Year))) +
  geom_boxplot(outlier.shape = NA)# +
  #geom_point(position=position_jitterdodge(),alpha=0.3)
  #geom_jitter(width=0.1,alpha=0.2)# +
  #facet_wrap(~Demographic)

```

## Highlight missing data

```{r}

# Missing data
no_approvals <- fda_approvals %>% 
  group_by(Approval_Year) %>% 
  summarize(Approvals = n()) 

reported_values <- fda_approvals_long %>% 
  filter(Percentage != "NA") %>% 
  filter(Demographic == "White" | Demographic == "Black" | Demographic == "Asian" | Demographic == "Hispanic") %>% 
  group_by(Approval_Year, Demographic) %>% 
  summarize(Non_NR = n() / 3) %>% 
  pivot_wider(names_from = Demographic, values_from = Non_NR, values_fill = 0)

missing_data <- data.frame(no_approvals$Approval_Year, 
                           no_approvals$Approvals, 
                           reported_values$Asian,
                           reported_values$Black,
                           reported_values$White,
                           reported_values$Hispanic)

names(missing_data) <- c("Approval_Year", "Approvals", "Asian", "Black", "White", "Hispanic")

missing_data <- missing_data %>% 
  mutate(Asian = round(100 * Asian / Approvals, 0),
         Black = round(100 * Black / Approvals, 0),
         White = round(100 * White / Approvals, 0),
         Hispanic = round(100 * Hispanic / Approvals, 0))

missing_data

```


```{r}

# Determine demographics to include in data quality assessment
demographics <- c("Female", 
                  "Age_65_or_older", 
                  "Asian",
                  "Black",
                  "Hispanic",
                  "White")

# Calculate total number of approvals by Year
num_approvals <- fda_approvals %>% 
  group_by(Approval_Year) %>% 
  summarise(Count = n())
num_approvals <- num_approvals$Count

# Grab number of non missing values by Demographic and Year
not_missing_values <- fda_approvals_long %>% 
  filter(Percentage != "NA") %>% 
  filter(Demographic %in% demographics)

not_missing_values <- not_missing_values %>% 
  group_by(Approval_Year, Demographic) %>% 
  summarise(Count = n()) %>% 
  pivot_wider(names_from = Demographic, values_from = Count, values_fill = 0)

not_missing_values <- not_missing_values[, c("Approval_Year", "Female", "Age_65_or_older", "Asian", "Black", "Hispanic", "White")]

# Subtract non missing from total to get number of missing values
missing_values <- num_approvals - not_missing_values

# Calculate % of entries which are missing
missing_values_percentage <- round(missing_values / num_approvals * 100)
missing_values_percentage$Approval_Year <- not_missing_values$Approval_Year # Copy the original Years to replace unecessary math done on the Year column

missing_values_percentage

```

### Disease burden comparison


```{r}

disease_burden <- read.csv('Disease_burden.csv')

# Read in data
approvals_short <- fda_approvals %>% select(Brand_Name, Therapeutic_Area, TA_subgroup, Indication, Asian, Black, Hispanic, White)
disease_burden <- disease_burden %>% filter(White != "NA")

#disease_of_choice <- "HIV-1"
#approvals_short <- approvals_short %>% filter(TA_subgroup == disease_of_choice)
#disease_burden <- disease_burden %>% filter(Indication == disease_of_choice)

# long
approvals_short <- approvals_short %>% pivot_longer(cols = Asian:White,
                                                    names_to = "Demographic",
                                                    values_to ="Enrollment")
#approvals_short <- approvals_short %>% filter(Enrollment != "NA")

# long disease burden
disease_burden <- disease_burden %>% pivot_longer(cols = Asian:White, 
                                                  names_to = "Demographic", 
                                                  values_to = "Burden")
disease_burden$Burden <- disease_burden$Burden * 100

# Index match
comparison_df <- right_join(approvals_short, disease_burden, 
                    by = c("Indication" = "Indication",
                           "Demographic" = "Demographic"))

# Make comparison
comparison_df <- comparison_df %>% 
  mutate(Comparison = case_when(
    Enrollment > Burden ~ "Over represented",
    Enrollment == Burden ~ "Appropriately represented",
    Enrollment < Burden ~ "Under represented",
    is.na(Enrollment) ~ "Demographic not collected in trial"
  ))

comparison_df_summary <- comparison_df %>% 
  group_by(Indication, Demographic, Comparison) %>% 
  summarise(Count = n())


ggplot(comparison_df_summary, aes(fill=Comparison, y=Count, x=Demographic, label = Count)) + 
  geom_bar(position="stack", stat="identity") +
  facet_wrap(~Indication) + 
  geom_text(size = 3, position = position_stack(vjust = 0.5))

```


# Check on disease burden

```{r}

# Read in data
approvals_short <- fda_approvals %>% select(Brand_Name, Approval_Year, Therapeutic_Area, TA_subgroup, Indication, Asian, Black, Hispanic, White)
disease_burden <- disease_burden %>% filter(White != "NA")

# Turn both data frames into long
approvals_short <- approvals_short %>% pivot_longer(cols = Asian:White,
                                                    names_to = "Demographic",
                                                    values_to ="Enrollment")
disease_burden <- disease_burden %>% pivot_longer(cols = Asian:White, 
                                                  names_to = "Demographic", 
                                                  values_to = "Burden")
disease_burden$Burden <- disease_burden$Burden * 100 # Multiply disease burden from percentage to ones

# Filter per user inputs
#if ( !is.null( input$race_TA_page ) | !is.null( input$ethnicity_TA_page ) ) { # Filter race and ethnicity
#    approvals_short <- approvals_short %>% 
#        filter( Demographic %in% input$race_TA_page | Demographic %in% input$ethnicity_TA_page )
#}

#if ( !is.null( input$year_TA_page ) ) { # Filter year
#    approvals_short <- approvals_short %>% 
#        filter( Approval_Year %in% input$year_TA_page )
#}

#if ( !is.null( input$therapeutic_area ) ) { # Filter by Therapeutic Area
#    approvals_short <- approvals_short %>% 
#        filter( Therapeutic_Area %in% input$therapeutic_area )
#}

# Merge the two df's along indication and demographic
comparison_df <- right_join(approvals_short, disease_burden, 
                            by = c("Therapeutic_Area" = "Therapeutic_Area", 
                                   "Indication" = "Indication",
                                   "Demographic" = "Demographic"))

# Make comparison
comparison_df <- comparison_df %>% 
    mutate(Comparison = case_when(
        Enrollment > Burden ~ "Over represented",
        Enrollment == Burden ~ "Appropriately represented",
        Enrollment < Burden ~ "Under represented",
        is.na(Enrollment) ~ "Demographic not collected in trial"
    ))

comparison_df_summary <- comparison_df %>% 
    group_by(Therapeutic_Area, Indication, Demographic, Comparison) %>% 
    summarise(Count = n())

```


